export const PokemonActionTypes = {
    SET_POKEMONS: 'SET_POKEMONS',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_ERROR: 'SET_ERROR',
    SET_CURRENT_POKEMON: 'SET_CURRENT_POKEMON',
    SET_FILTER: 'SET_FILTER',
}